version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mean-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: mean-backend
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/mean-db
      - PORT=5000
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: mean-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  mongo_data:

